version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - 7000:7000
    restart: always

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    restart: always
    command: celery -A celery worker --loglevel=INFO

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always
